version: '3'
services:
 docker-app:
    image: lindomar/imagem-projeto
    ports:
      - "8080:8080"    
    depends_on:
      - docker-postgres
 docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=pedido
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=teste
    ports:
      - "5433:5432"        